### PR TITLE
Configuration for `MiniProdN1.1` NDLAr only

### PR DESCRIPTION
**Pull request by alexbooth92**
Setting up `specs/*`, `slurm/*` and `examples/*` for `MiniProdN1.1` NDLAr only. It pairs with [this PR](https://github.com/DUNE/2x2_sim/pull/19). This setup should allow us to:

- Pass a single geometry to the (fiducial, rock) x (generation, edepsim) stages (below, a copy now at NERSC).
```
/cvmfs/dune.opensciencegrid.org/products/dune/ND_Production/v01_05_00/gdml/nd_hall_with_lar_tms_sand.gdml
```
- Generate single fiducial interactions by specifying `volArgonCubeDetector75` as the top volume. This is what was done last time according to [this](https://dunescience.slack.com/archives/CKXSC8EG3/p1656608519830749) slack message.
- Generate single rock interactions using the "rockbox" method developed by Palash. Details [here](https://github.com/DUNE/ND_Production/pull/13).
- Run `edepsim` in the single geometry.
- Build spills which include both rock and fiducial interactions, all of which respect the timing structure and beam intensity of the LBNF beam.
- During the conversion to h5 file format, only interactions which have produced energy deposits in the sensitive volume `TPCActive_shape` are taken forward.

Note that `specs/MiniProdN1p1_NDLAr/MiniProdN1p1_NDLAr_1E19_RHC.larnd.yaml` is likely to change. The `ndlar-sim` step has not been nailed down yet.

### CODE REVIEW

**Comment by mjkramer** [comment]
> Am I on the general right track?

Yes! One change I'd suggest would be to get rid of `slurm/MiniProdN1p1_NDLAr`. If you go back to `examples/submit_MiniRun3.sh`, near the end, you'll see that I got sick of all of the repetitive `slurm` scripts and switched to a couple of generic scripts, `slurm/fw_cpu.slurm.sh` and `slurm/fw_gpu.slurm.sh` (the latter used for larnd-sim). You can just pass them to `sbatch` in `submit_MiniProdN1p1_NDLAr.sh`.

> References to arcubepro, [here](https://github.com/lbl-neutrino/fireworks4dune/blob/339e512336a66ff05b27f5810af45e14118eceb9/fw_config/templates/my_launchpad.template.yaml#L1) for example, will this need to change and what impact will this have on database access?

In the local git clone from which commands are actually being run, this file needs to be copied to `my_launchpad.yaml` and the DB password needs to specified. Once that is done, the correct Mongo DB server will be used (as long as the `FW_CONFIG_FILE` env var is set to that `my_launchpad.yaml`, e.g. as done by `admin/load_fireworks.sh`). Any old Mongo server can be used; after tweaking `my_launchpad.yaml`, run `lpad init` to set up the FireWorks "collections" (i.e. tables) and you're good to go. I'll Slack you the details for a test server you can use.

> Perhaps related to the bullet above - what determines which allocation gets spent?

That's determined by the line `#SBATCH --account=dune` at the top of the `slurm` scripts.

> Flux files I think are just the same?

I think we need to dig up the appropriate LBNF flux files, since we've been using the NuMI flux for the 2x2 simulation.

> ARCUBE_TUNE (genie tune) the same?

Yes, AFAIK we can / should be using the same tune for both 2x2 and NDLAr. I'm in the process of switching to the new DUNE base model (and a new GENIE build) for the 2x2, so `ARCUBE_TUNE` (as well as `ARCUBE_CONTAINER`) are "in flux" (sorry).

> For generation, fiducial events will use volArgonCubeActive as the top volume and rock events will use the https://github.com/DUNE/ND_Production/pull/13 developed by Palash (was this ever used in production mode - code still living in a branch?).

If I understand correctly, this setup will not include any events that originate in TMS or SAND or the passive parts of NDLAr, etc. But if we use `volDetEnclosure` as the top volume for the "fiducial" sample, along with a rock box sample, then I think we won't miss anything. Of course, then the "fiducial" sample will really be a "fiducial-plus" sample, but oh well.

I know basically nothing about the history of ND production, so I have no idea if the rock box was actually used. In the longer term, it would be nice if the 2x2 and ND productions could use a common approach for the rock muons. Whether the rock box or the "rock-only geometry" approaches are better, I don't know. It's an interesting question.

**Comment by jdkio** [comment]
Is there a reason you're running on volArgonCubeActive instead of volDetEnclosure? The latter gives you TMS-only events too, as well as sand. 

Are you simulating a full spill or single events? If a full spill, you probably want the additional TMS-only events as a background.

**Comment by alexbooth92** [comment]
> Is there a reason you're running on volArgonCubeActive instead of volDetEnclosure? The latter gives you TMS-only events too, as well as sand.

As far as I know, we want events _only_ in ND LAr.

**Comment by jdkio** [comment]
> As far as I know, we want events _only_ in ND LAr.

We want to match the data. The data will have TMS-only events as a background.

**Comment by alexbooth92** [comment]
A few minor changes may be necessary but I think this PR is mostly good to go.

**Review by mjkramer — APPROVED** [review]

**Pull request merged**
